# For development environment
development:
  adapter: postgresql
  encoding: unicode
  database: mytestapp
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  port: 5432


# For development environment
production:
  adapter: postgresql
  encoding: unicode
  database: mytestapp
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  port: 5432